### ISSUE TITLE
Cannot install due to missing README

### ISSUE THREAD

**Issue by chrisburr** [TheSnakePit/boa#1]
The readme is used in the setup.py but doesn't exist here causing `pip install git+https://github.com/TheSnakePit/boa.git` to fail.

https://github.com/TheSnakePit/boa/blob/d9873c9e04eb3be2c4abf7a5ffa1dd2bfc5da228/setup.py#L20

**Comment by wolfv** [comment]
ouch.

**Comment by wolfv** [comment]
this is fixed now :)

I am also releasing a new version of mamba, which allows to reload repositories so that multiple outputs can be handled.

**Comment by chrisburr** [comment]
Great, thanks :)

I built mamba from source yesterday so I could use `boa` (I didn't realise it was only failing because I have multiple outputs). Everything else has worked so far 🤞
