### ISSUE TITLE
Cache not loaded

### ISSUE THREAD

**Issue by Tobias-Fischer** [TheSnakePit/boa#16]
When trying to `conda mambabuild .` with vinca, I get the following error:

```
Traceback (most recent call last):
  File "/Users/tobias/opt/anaconda3/bin/conda-mambabuild", line 33, in <module>
    sys.exit(load_entry_point('boa', 'console_scripts', 'conda-mambabuild')())
  File "/Users/tobias/robot/boa/boa/cli/mambabuild.py", line 284, in main
    solver.replace_channels()
  File "/Users/tobias/robot/boa/boa/cli/mambabuild.py", line 151, in replace_channels
    cp = subdir.cache_path()
RuntimeError: Cache not loaded!
```

Any hints why that would be?

**Comment by wolfv** [comment]
thanks for opening the bug.
yeah, that's probably that you don't (yet) have a conda-bld folder with a repodata in a subdir. Will have to add some safeguards around that! :)

Btw. we have a branch that generates "new-style" recipes from vinca for boa, that can be used wtih `boa build .`

We're trying to get the franka package to build + moveit. Unfortunately that (franka) is not yet on noetic ...

**Comment by xhochy** [comment]
I get the same error on OSX because it cannot find repodata for `linux-64`. Seems like the hardcoded subdir is the issue: https://github.com/TheSnakePit/boa/blob/ccb5ab5f4bdebf25ced6f94f939a97d65ba7d13f/boa/cli/mambabuild.py#L283

**Comment by Tobias-Fischer** [comment]
Ahhh yes, I'm on osx too. I should have mentioned that! I can create a PR for osx if you want, but I'm not sure about windows ..

**Comment by wolfv** [comment]
right, that makes sense! Actually, `conda-forge` is also currently hard coded... We just need to use the function from conda to do this...

https://github.com/TheSnakePit/boa/blob/3bb933e6f3fe9fcc9a25718485f0cd898ad77edd/boa/cli/boa.py#L802

maybe context.platform has the right value?

**Comment by wolfv** [comment]
so 

```
from conda.base import context
c = context.Context()
c.subdirs
>>> ('linux-64', 'noarch')
```

shoudl be the function to get the native subdirs to consider.

**Comment by wolfv** [comment]
a PR would be highly appreciated @Tobias-Fischer

**Comment by wolfv** [comment]
I tried to delete my local conda-build folder several times, and fixed another bug related to the initialization and usage of update_index. I hope with current master starting from a "blank" state should be fine, and OS X / win should also work out of the box.

**Comment by Tobias-Fischer** [comment]
Thanks a lot @wolfv!
