### ISSUE TITLE
Specification X.Y is interpreted as X.Y.0

### ISSUE THREAD

**Issue by chrisburr** [TheSnakePit/boa#3]
This might be another issue you know about but I'll dump it here never the less :)

Version requirements like `X.Y` are interpreted as `X.Y.0` instead of `X.Y.*`. I've seen this with `python 3.7` using `3.7.0` and `numpy 1.14` using `1.14.0`. These versions avoid the issue in #2 but result in linker errors due to the pinnings not being quite right.

**Comment by wolfv** [comment]
yes, indeed, this is one of the major differences between mamba and conda. 

We just need to add an `3.7.*` and it should work fine

**Comment by wolfv** [comment]
I tried to change thsi behavior here: 

https://github.com/TheSnakePit/boa/blob/6be7d4c7ef19e67a1e7aae2cf48be6a5280d0f8f/boa/cli/build.py#L227-L231

Let me know if that works for you!
