### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel.yaml'

### ISSUE THREAD

**Issue by hugobuddel** [TheSnakePit/boa#9]
Experimenting with boa gives me this error (running from the project directory:
```
$ boa .
Traceback (most recent call last):
  File "/opt/conda/bin/boa", line 33, in <module>
    sys.exit(load_entry_point('boa', 'console_scripts', 'boa')())
  File "/opt/conda/bin/boa", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/test/boa/boa/cli/render.py", line 2, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel.yaml'
```

Installing `ruamel` and `ruamel_yaml` does not help (adapted from the readme):
```
mamba install conda-build colorama pip ruamel ruamel_yaml -c conda-forge
```

**Comment by wolfv** [comment]
thanks! Do you want to make a PR to fix the README?

**Comment by hugobuddel** [comment]
I have not got it to work properly, and I can't really figure out what is going on. (But the edit window with the README was already open!)

E.g. there is a similar question on StackOverflow about conda itself: https://stackoverflow.com/questions/41373834/conda-importerror-no-module-named-ruamel-yaml-comments

**Comment by wolfv** [comment]
yeah there might be some issue when mixing the pip and conda packages... I remember something with this particular package.
Maybe the correct package is https://anaconda.org/conda-forge/ruamel.yaml from conda-forge and not `ruamel_yaml`?

**Comment by wolfv** [comment]
so `ruamel.yaml`

**Comment by wolfv** [comment]
btw just as a heads-up, the commands also changed. 

it's now 

```
conda mambabuild blabla
```

and

```
boa render recipes/libsolv
boa build recipes/libsolv
```

and it _will_ be super buggy :)

**Comment by hugobuddel** [comment]
Thanks for the heads up!

Indeed seems a bit buggy, I have not got it to work yet. Our CI spends about 10 minutes creating conda environments in conda-build. The actual tests take only a few minutes. So I'm experimenting a bit with mamba/boa to see whether we can speed things up with mamba/boa.

**Comment by wolfv** [comment]
feel free to show me a link to your recipe and I can give it a try (if it's open source).

**Comment by hugobuddel** [comment]
It's 'not yet' open source, for quite some time now (not really in my hands).. Got it to work now it seems! see #11 .

**Comment by wolfv** [comment]
cool! are you using "boa" or the `conda mambabuild`?

**Comment by hugobuddel** [comment]
Using `conda mambabuild`. My recipe is `conda-recipe/meta.yaml`, and I have no `recipe.yaml`, so boa doesn't seem to know what to do.

The recipe is online by the way: https://gitlab.astro-wise.org/micado/micadowise/-/blob/standardcado/conda-recipe/meta.yaml
But our channel is not, because it has some dependencies cannot distribute, so you cannot build the recipe unfortunately.
